button_pointer = noone;
first_action = noone;
now_layer = noone;
min_layer = noone;
max_layer = noone; 
which_character = noone;
which_action = noone;
which_enemy = noone;
last_mov = "right";
action_counter = global.number + 1;
actors = [noone, noone, noone, noone];
enemies_turn = false;
cadaver_counter = 0;
begin_battle();
