button_pointer = noone;
first_action = noone;
first_enemy = noone;
now_layer = noone;
min_layer = noone;
max_layer = noone; 
which_character = noone;
which_action = noone;
last_mov = noone;
action_counter = global.number + 1;
actors = [noone, noone, noone, noone];
begin_battle();
first_enemy = enemies[0];
